### ISSUE TITLE
PyTrx not in conda environment dependencies?

### ISSUE THREAD

**Issue by AdrienWehrle** [PennyHow/PyTrx#37]
Hi Penny,

I was wondering why `PyTrx` is not included in your `environment.yml`?

Thank you a lot in advance and have a nice day!

**Comment by PennyHow** [comment]
Hi Adrian,

The environment.yml is for set-up from the repository i.e.

```bash
conda env create -f environment.yml
git clone https://github.com/PennyHow/PyTrx.git
```

With `pip install pytrx`, the dependencies are automatically installed hence an environment set-up from the .yml file is not needed (although you have to be careful installing gdal, as it can have big clashes with opencv - I'm working on this to be a bit easier in the next release).

**Comment by AdrienWehrle** [comment]
Hi Penny,

Thank you a lot for your answer! That makes sense, I thought it was more like a work environment! I'd also just be curious to know if you are planning to include `PyTrx` in `conda-forge` at some point? This would prevent potential known issues from occurring when using `pip` with `conda` (for users installing the library through `pip` in a `conda` virtual environment). And also help to better deal with potential conflicts with sensitive libraries like `gdal`.

**Comment by PennyHow** [comment]
Yes, I've actually just been looking into `conda-forge` recipes for the next release of PyTrx (although never done it myself, so learning on the job!) I'm just refining some parts for the release of v1.2 (which will be soon), but think v2.0 will have installation from `pip` or `conda-forge`. 

My hope is that v2.0 moves away from `gdal` so that the set-up is easier for users. Most user queries are about the set-up rather than running PyTrx itself, so it's something that has already been in the back of my mind for the next release.

**Comment by AdrienWehrle** [comment]
Awesome, thanks a lot for your answer! Looking forward to seeing your solution(s) to move away from `gdal`!
