### ISSUE TITLE
Cannot run calcDenseVelocity with campars=None

### ISSUE THREAD

**Issue by karunasah** [PennyHow/PyTrx#43]
https://github.com/PennyHow/PyTrx/blob/cd614be2ea3800095ce7eadbe018580a04e55397/PyTrx/Velocity.py#L674

calcDenseVelocity should be able to run with campars = None but, campars is indexed as a list therefore runs into an error if it is not supplied. I wanted to run calcDenseVelocity on two orthoimages resampled in the same grid, and therefore did not need any camera parameters or DEMs. The docstring suggests that the function can be run without campars. It should be stated clearly whether or not campars is needed for the function.

**Comment by PennyHow** [comment]
Thanks for flagging this. We have now added additional functionality, with image grid seeding and DEM grid seeding - `seedGridIM` and `seedGridDEM`. So now, if the `campars` variable is `None` then the grid will be seeded from the image rather than the input DEM. 

https://github.com/PennyHow/PyTrx/blob/a4fb76986dda98b5432c43d65c704915cafc2904/PyTrx/Velocity.py#L677-L680

I'd really like you to check that this is working before we put it into the next PyTrx release. Please could you clone the newest version of our [development branch](https://github.com/PennyHow/PyTrx/tree/dev), and see if it works with your workflow.
